- build: examples/i2c_bme280
  photon: [0.6.3, 0.7.0, 0.8.0-rc.12, 1.0.0, latest]
  p1: [latest]
  electron: [0.7.0, 1.0.0, latest]
  argon: [0.8.0-rc.27, 0.9.0, latest]
  boron: [latest]
- build: examples/spi_bme280
  photon: [latest]
  p1: [latest]
  electron: latest]
  argon: [latest]
  boron: [latest]
- build: examples/i2c_Wire1
  electron: [latest]
  